In [21]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from check import parse_logs

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [43]:
# Путь к файлу логов
log_file = "Explore-logs-2025-02-21 12_57_45.json"
    
# Парсим логи
df = parse_logs(log_file)
    
df

,timestamp,algorithm_name,city_id,start_price,rec_price,bidding_steps,distance,duration,eta,round_value,max_bidding_price,multiplier,available_prices,span_id,trace_id,default_prices,exp_prices,exp_prices_no_round
0,2025-02-21T12:57:14.528Z,bid_mph,4547,2500,2500,"[15, 25, 40]",10764,642,60,100,10000000,100,"[26.0, 27.0, 28.0]",c3e5efbea9abcedf,5bb8ac6b3a18419da0d1ddf85a553b40,"[29.0, 32.0, 35.0]","[26.0, 27.0, 28.0]","[25.778816199376948, 26.557632398753896, 27.33..."
1,2025-02-21T12:57:14.519Z,bid_mph,4547,2500,2500,"[15, 25, 40]",10764,642,24,100,10000000,100,[26.0],9fa54fd6f8db4434,1d6df2f42b084861aad8e48e70cac5fe,"[29.0, 32.0, 35.0]",[26.0],"[25.31152647975078, 25.62305295950156, 25.9345..."
2,2025-02-21T12:57:14.336Z,bid_mph,4547,2500,2500,"[15, 25, 40]",10764,642,69,100,10000000,100,"[26.0, 27.0, 28.0]",e87df72828c7cf1b,fdca475e3bf94a6591f1310b0f2a82cc,"[29.0, 32.0, 35.0]","[26.0, 27.0, 28.0]","[25.89563862928349, 26.79127725856698, 27.6869..."
3,2025-02-21T12:57:14.044Z,bid_mph,4547,2500,2500,"[15, 25, 40]",10764,642,26,100,10000000,100,[26.0],0b9bd82e27b495df,59afb525c6fe49a6b87edf41f6be7913,"[29.0, 32.0, 35.0]","[26.0, 27.0]","[25.33748701973001, 25.67497403946002, 26.0124..."
4,2025-02-21T12:57:13.987Z,bid_mph,4547,2500,2500,"[15, 25, 40]",10764,642,25,100,10000000,100,[26.0],ef33b0d89bbcb6bd,806ad82e9d4f4129871a55db4d5dae30,"[29.0, 32.0, 35.0]",[26.0],"[25.324506749740394, 25.649013499480787, 25.97..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2025-02-21T12:55:27.422Z,bid_mph,4547,700,900,"[15, 25, 40]",1628,150,62,100,10000000,100,"[9.0, 10.0]",4d864960e389ff73,90e98b5cb04147f59e2ff77ddf2bb847,"[9.0, 10.0]","[9.0, 11.0, 13.0]","[8.906666666666666, 10.813333333333333, 12.72]"
496,2025-02-21T12:55:27.202Z,bid_mph,4547,700,900,"[15, 25, 40]",1628,150,62,100,10000000,100,"[9.0, 10.0]",fd7dba703d76f91c,8bd8ad94cd42412d8d59a3ae79e44316,"[9.0, 10.0]","[9.0, 11.0, 13.0]","[8.906666666666666, 10.813333333333333, 12.72]"
497,2025-02-21T12:55:27.163Z,bid_mph,4547,1200,1400,"[15, 25, 40]",4319,351,106,100,10000000,100,"[14.0, 15.0, 17.0]",3c8619f4b2fd0644,0960c4912a7f4cd0a2e6dc82ca98814a,"[14.0, 15.0, 17.0]","[15.0, 17.0, 19.0]","[14.075973409306744, 16.151946818613485, 18.22..."
498,2025-02-21T12:55:27.097Z,bid_mph,4547,700,900,"[15, 25, 40]",1628,150,166,100,10000000,100,"[9.0, 10.0]",39398b6a36a79786,a910f39042ab4168bedee053a95ce0a3,"[9.0, 10.0]","[11.0, 15.0, 19.0]","[10.986666666666668, 14.973333333333334, 18.96]"
499,2025-02-21T12:55:27.044Z,bid_mph,4547,700,900,"[15, 25, 40]",1628,150,102,100,10000000,100,"[9.0, 10.0]",4b10a514282f5841,10476fb337724df590e7ff33705c3ada,"[9.0, 10.0]","[10.0, 13.0, 16.0]","[9.706666666666667, 12.413333333333334, 15.12]"

In [45]:
df[df['span_id'] == 'df3e530fb1f67d3a']

,timestamp,algorithm_name,city_id,start_price,rec_price,bidding_steps,distance,duration,eta,round_value,max_bidding_price,multiplier,available_prices,span_id,trace_id,default_prices,exp_prices,exp_prices_no_round
333,2025-02-21T12:56:09.721Z,bid_mph,4547,700,700,"[15, 25, 40]",4041,284,264,100,10000000,100,"[9.0, 10.0]",df3e530fb1f67d3a,8d576a2c9d4949ed9120374dfa434690,"[9.0, 10.0]","[10.0, 12.0, 14.0]","[9.169014084507042, 11.338028169014086, 13.507..."

In [33]:
# df[df['available_prices'] != df['exp_prices']]
df[[x[-1] < y[-1] for x, y in zip(df['exp_prices'], df['available_prices'])]]

Empty DataFrame
Columns: [timestamp, algorithm_name, city_id, start_price, rec_price, bidding_steps, distance, duration, eta, round_value, max_bidding_price, multiplier, available_prices, default_prices, exp_prices, exp_prices_no_round]
Index: []

In [39]:
# Проверяем строки, где available_prices отличается и от default_prices, и от exp_prices
df[~(df['available_prices'].apply(lambda x: sorted(x)) == df['default_prices'].apply(lambda x: sorted(x))) & 
   ~(df['available_prices'].apply(lambda x: sorted(x)) == df['exp_prices'].apply(lambda x: sorted(x)))]

# Для более детального анализа можно посмотреть значения для первых нескольких таких строк:
problematic_rows = df[~(df['available_prices'].apply(lambda x: sorted(x)) == df['default_prices'].apply(lambda x: sorted(x))) & 
                     ~(df['available_prices'].apply(lambda x: sorted(x)) == df['exp_prices'].apply(lambda x: sorted(x)))]

if not problematic_rows.empty:
    print("\nДетальный анализ первой проблемной строки:")
    row = problematic_rows.iloc[0]
    print(f"available_prices: {row['available_prices']}")
    print(f"default_prices:   {row['default_prices']}")
    print(f"exp_prices:       {row['exp_prices']}")

Детальный анализ первой проблемной строки:
available_prices: [26.0]
default_prices:   [29.0, 32.0, 35.0]
exp_prices:       [26.0, 27.0]

In [46]:
# Получаем проблемные строки
problematic_rows = df[~(df['available_prices'].apply(lambda x: sorted(x)) == df['default_prices'].apply(lambda x: sorted(x))) & 
   ~(df['available_prices'].apply(lambda x: sorted(x)) == df['exp_prices'].apply(lambda x: sorted(x)))]

# Создаем словарь с идентификаторами
ids = {
    'trace_ids': problematic_rows['trace_id'].tolist(),
    'span_ids': problematic_rows['span_id'].tolist()
}

# Сохраняем в JSON файл
import json
with open('problematic_ids.json', 'w') as f:
    json.dump(ids, f, indent=2)

# Выводим DataFrame для просмотра
problematic_rows

,timestamp,algorithm_name,city_id,start_price,rec_price,bidding_steps,distance,duration,eta,round_value,max_bidding_price,multiplier,available_prices,span_id,trace_id,default_prices,exp_prices,exp_prices_no_round
3,2025-02-21T12:57:14.044Z,bid_mph,4547,2500,2500,"[15, 25, 40]",10764,642,26,100,10000000,100,[26.0],0b9bd82e27b495df,59afb525c6fe49a6b87edf41f6be7913,"[29.0, 32.0, 35.0]","[26.0, 27.0]","[25.33748701973001, 25.67497403946002, 26.0124..."
15,2025-02-21T12:57:11.867Z,bid_mph,4547,2500,2500,"[15, 25, 40]",10764,642,26,100,10000000,100,[26.0],516c09ddfbcaad83,8441f1e7e10f46009f4828b46983c080,"[29.0, 32.0, 35.0]","[26.0, 27.0]","[25.33748701973001, 25.67497403946002, 26.0124..."
18,2025-02-21T12:57:11.708Z,bid_mph,4547,2500,2500,"[15, 25, 40]",10764,642,26,100,10000000,100,[26.0],f4ad6e49d8ca0248,676272c4bd634a6183975b7ddb5612ff,"[29.0, 32.0, 35.0]","[26.0, 27.0]","[25.33748701973001, 25.67497403946002, 26.0124..."
46,2025-02-21T12:56:57.365Z,bid_mph,4547,1100,1100,"[15, 25, 40]",8111,573,53,100,10000000,100,[12.0],48a29fc13aa9f414,e0d397b12fc74930b5de63a3733eb59f,"[13.0, 14.0, 16.0]","[12.0, 13.0]","[11.3391506689936, 11.678301337987202, 12.0174..."
80,2025-02-21T12:56:52.325Z,bid_mph,4547,1100,1100,"[15, 25, 40]",8111,573,53,100,10000000,100,[12.0],a1532fdf009006bb,8ac8486dbeb5461d822ffbb97c30fa19,"[13.0, 14.0, 16.0]","[12.0, 13.0]","[11.3391506689936, 11.678301337987202, 12.0174..."
87,2025-02-21T12:56:50.154Z,bid_mph,4547,1100,1100,"[15, 25, 40]",8111,573,53,100,10000000,100,[12.0],f2c2e7832e3b5e52,4ab0d68e6e3f4ce5913ad8a07976b059,"[13.0, 14.0, 16.0]","[12.0, 13.0]","[11.3391506689936, 11.678301337987202, 12.0174..."
99,2025-02-21T12:56:47.995Z,bid_mph,4547,1100,1100,"[15, 25, 40]",8111,573,53,100,10000000,100,[12.0],a96c11dd464d956d,53b5ab7ee9fc41ed9a7ac59ab429f502,"[13.0, 14.0, 16.0]","[12.0, 13.0]","[11.3391506689936, 11.678301337987202, 12.0174..."
103,2025-02-21T12:56:47.817Z,bid_mph,4547,1100,1100,"[15, 25, 40]",8111,573,53,100,10000000,100,[12.0],7c141e65ff5b8d81,7a46f9b995574e83b80cfcd184ffb4d9,"[13.0, 14.0, 16.0]","[12.0, 13.0]","[11.3391506689936, 11.678301337987202, 12.0174..."
431,2025-02-21T12:55:57.558Z,bid_mph,4547,1500,1500,"[15, 25, 40]",6073,439,132,100,10000000,100,"[17.0, 18.0, 20.0]",2869c13aec75f106,0d8a021b17fb4cf0b356ca5ceb0210d6,"[18.0, 19.0, 21.0]","[17.0, 19.0, 20.0]","[16.503416856492027, 18.006833712984054, 19.51..."
433,2025-02-21T12:55:57.380Z,bid_mph,4547,1500,1500,"[15, 25, 40]",6073,439,132,100,10000000,100,"[17.0, 18.0, 20.0]",27f532a5a2a348e1,9306f5ae957446c88f6da2dc5f603a55,"[18.0, 19.0, 21.0]","[17.0, 19.0, 20.0]","[16.503416856492027, 18.006833712984054, 19.51..."